# Generated by Django 5.1.15 on 2026-04-28 07:24

import apps.accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('learning', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=128, verbose_name='ФИО')),
                ('parent_phone', models.CharField(max_length=16, validators=[apps.accounts.validators.validate_phone], verbose_name='телефон родителя')),
                ('grade', models.IntegerField(choices=[(10, '10'), (11, '11')], verbose_name='класс')),
                ('learning_language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Қазақ')], max_length=8, verbose_name='язык обучения')),
                ('target_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='целевой балл')),
                ('current_level', models.PositiveIntegerField(default=0, verbose_name='текущий уровень')),
                ('sales_status', models.CharField(choices=[('new', 'Новый'), ('in_work', 'В работе'), ('registered', 'Оформил'), ('paid', 'Оплатил'), ('renewal', 'На продление'), ('rejected', 'Отказ')], db_index=True, default='new', max_length=16, verbose_name='статус продаж')),
                ('assigned_curator', models.ForeignKey(blank=True, limit_choices_to={'role': 'curator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_students', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='universities.city')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='universities.region')),
                ('selected_subjects', models.ManyToManyField(blank=True, related_name='interested_students', to='learning.subject')),
                ('target_specialities', models.ManyToManyField(blank=True, related_name='aspiring_students', to='universities.speciality')),
                ('target_universities', models.ManyToManyField(blank=True, related_name='aspiring_students', to='universities.university')),
            ],
            options={
                'verbose_name': 'Профиль ученика',
                'verbose_name_plural': 'Профили учеников',
            },
        ),
        migrations.CreateModel(
            name='CuratorAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='назначен')),
                ('unassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='снят')),
                ('curator', models.ForeignKey(limit_choices_to={'role': 'curator'}, on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator_history', to='profiles.studentprofile')),
            ],
            options={
                'verbose_name': 'Назначение куратора',
                'verbose_name_plural': 'Назначения кураторов',
                'ordering': ('-assigned_at',),
                'indexes': [models.Index(fields=['student', '-assigned_at'], name='profiles_cu_student_71e471_idx')],
            },
        ),
    ]
