# Generated by Django 5.1.15 on 2026-04-28 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='название')),
                ('name_kk', models.CharField(max_length=128, null=True, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена (KZT)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='срок (дней)')),
                ('has_learning', models.BooleanField(default=True, verbose_name='доступ к обучению')),
                ('has_testing', models.BooleanField(default=True, verbose_name='доступ к ЕНТ-тестам')),
                ('has_ai_tutor', models.BooleanField(default=False, verbose_name='доступ к AI Tutor')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('subjects', models.ManyToManyField(blank=True, related_name='tariffs', to='learning.subject')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('expired', 'Истекла'), ('cancelled', 'Отменена')], default='active', max_length=16, verbose_name='статус')),
                ('source', models.CharField(choices=[('self_payment', 'Самостоятельная оплата'), ('via_curator', 'Через куратора'), ('via_manager', 'Через менеджера')], default='self_payment', max_length=16, verbose_name='источник')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='начало')),
                ('expires_at', models.DateTimeField(verbose_name='истекает')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.tariff')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма (KZT)')),
                ('method', models.CharField(choices=[('card', 'Карта'), ('kaspi_qr', 'Kaspi QR'), ('halyk_qr', 'Halyk QR'), ('manual', 'Вручную')], max_length=16, verbose_name='способ')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('success', 'Успех'), ('failed', 'Не прошёл')], default='pending', max_length=16, verbose_name='статус')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='id у провайдера')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='дата оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.subscription')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_7a85fd_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='payments_su_user_id_058311_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='unique_active_subscription_per_user'),
        ),
    ]
