# Generated by Django 5.1.15 on 2026-04-28 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='код')),
                ('title', models.CharField(max_length=256, verbose_name='заголовок')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='заголовок')),
                ('title_kk', models.CharField(max_length=256, null=True, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='текст')),
                ('body_ru', models.TextField(null=True, verbose_name='текст')),
                ('body_kk', models.TextField(null=True, verbose_name='текст')),
                ('channels', models.JSONField(default=list, help_text='список каналов: ["in_app", "whatsapp"]', verbose_name='каналы')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('in_app', 'В приложении'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=16, verbose_name='канал')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('read', 'Прочитано'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='статус')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='контекст')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='отправлено')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='прочитано')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['status'], name='notificatio_status_d92267_idx')],
            },
        ),
    ]
