# Generated by Django 5.1.15 on 2026-04-28 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='номер класса')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='название урока')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='название урока')),
                ('title_kk', models.CharField(max_length=256, null=True, verbose_name='название урока')),
                ('video_url', models.URLField(blank=True, verbose_name='видео')),
                ('theory', models.TextField(blank=True, verbose_name='теория')),
                ('theory_ru', models.TextField(blank=True, null=True, verbose_name='теория')),
                ('theory_kk', models.TextField(blank=True, null=True, verbose_name='теория')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('content_status', models.CharField(choices=[('new', 'Новый'), ('review', 'Экспертиза'), ('approved', 'Одобрен'), ('published', 'Опубликован')], default='new', max_length=16, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('topic__section__order', 'topic__order', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='название')),
                ('name_kk', models.CharField(max_length=128, null=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('icon', models.CharField(blank=True, max_length=128, verbose_name='иконка (slug или url)')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PracticeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('single_choice', 'Один правильный'), ('multi_choice', 'Несколько правильных'), ('match', 'На соответствие'), ('context', 'Контекстное')], max_length=16, verbose_name='тип')),
                ('payload', models.JSONField(default=dict, verbose_name='данные задания')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_tasks', to='learning.lesson')),
            ],
            options={
                'verbose_name': 'Практическое задание',
                'verbose_name_plural': 'Практические задания',
                'ordering': ('lesson', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='learning.lesson')),
            ],
            options={
                'verbose_name': 'Мини-тест',
                'verbose_name_plural': 'Мини-тесты',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('single_choice', 'Один правильный'), ('multi_choice', 'Несколько правильных'), ('match', 'На соответствие'), ('context', 'Контекстное')], max_length=16, verbose_name='тип')),
                ('text', models.TextField(verbose_name='текст вопроса')),
                ('options', models.JSONField(default=list, verbose_name='варианты ответа')),
                ('correct_answers', models.JSONField(default=list, verbose_name='правильные ответы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.quiz')),
            ],
            options={
                'verbose_name': 'Вопрос мини-теста',
                'verbose_name_plural': 'Вопросы мини-теста',
                'ordering': ('quiz', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('name_ru', models.CharField(max_length=256, null=True, verbose_name='название')),
                ('name_kk', models.CharField(max_length=256, null=True, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning.subject')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ('subject__name', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('name_ru', models.CharField(max_length=256, null=True, verbose_name='название')),
                ('name_kk', models.CharField(max_length=256, null=True, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.section')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ('section__order', 'order'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.topic'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stars', models.PositiveSmallIntegerField(default=0, verbose_name='звёзды (0-3)')),
                ('best_quiz_score', models.PositiveSmallIntegerField(default=0, verbose_name='лучший балл (%)')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='кол-во попыток')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='завершён')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя попытка')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс по уроку',
                'verbose_name_plural': 'Прогресс по урокам',
                'indexes': [models.Index(fields=['user', '-last_attempt_at'], name='learning_le_user_id_be7280_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='балл (%)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='конец')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Попытка мини-теста',
                'verbose_name_plural': 'Попытки мини-тестов',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['user', 'quiz', '-started_at'], name='learning_qu_user_id_e2269a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['content_status'], name='learning_le_content_972993_idx'),
        ),
    ]
