# Generated by Django 5.1.15 on 2026-04-29 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(blank=True, default=list, help_text='Снапшот ответов: [{question_id, value, is_correct}, ...]', verbose_name='ответы ученика'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='correct_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='верных ответов'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('finished', 'Завершена'), ('expired', 'Истекла')], db_index=True, default='in_progress', max_length=16, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='всего вопросов'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user', 'quiz'), name='unique_active_quiz_attempt'),
        ),
    ]
