# Generated by Django 5.1.15 on 2026-04-28 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('helper', 'Помощник'), ('learning', 'Обучение'), ('grant_search', 'Поиск гранта')], default='helper', max_length=16, verbose_name='режим')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='начало')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Диалог с AI Tutor',
                'verbose_name_plural': 'Диалоги с AI Tutor',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'AI')], max_length=16, verbose_name='роль')),
                ('content', models.TextField(verbose_name='контент')),
                ('helpful_rating', models.CharField(blank=True, choices=[('positive', 'Полезно'), ('negative', 'Не нашёл ответ')], max_length=16, verbose_name='оценка')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_tutor.conversation')),
            ],
            options={
                'verbose_name': 'Сообщение AI Tutor',
                'verbose_name_plural': 'Сообщения AI Tutor',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-started_at'], name='ai_tutor_co_user_id_740587_idx'),
        ),
    ]
