# Generated by Django 5.1.15 on 2026-04-28 07:24

import apps.accounts.managers
import apps.accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(help_text='В формате E.164, напр. +77001234567', max_length=16, unique=True, validators=[apps.accounts.validators.validate_phone], verbose_name='телефон')),
                ('role', models.CharField(choices=[('student', 'Ученик'), ('curator', 'Куратор'), ('content_manager', 'Контент-менеджер'), ('sales_manager', 'Менеджер по продажам'), ('super_admin', 'Супер-админ')], db_index=True, default='student', max_length=32, verbose_name='роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='персонал')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=16, verbose_name='телефон')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('success', models.BooleanField(default=False, verbose_name='успех')),
                ('failure_reason', models.CharField(blank=True, max_length=64, verbose_name='причина неудачи')),
                ('user', models.ForeignKey(blank=True, help_text='null если попытка входа была с несуществующим телефоном', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие входа',
                'verbose_name_plural': 'События входа',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['phone', '-created_at'], name='accounts_lo_phone_d2230b_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['success', '-created_at'], name='accounts_lo_success_528c82_idx'),
        ),
    ]
