# Generated by Django 5.1.15 on 2026-04-28 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='название')),
                ('name_kk', models.CharField(max_length=128, null=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='название')),
                ('name_kk', models.CharField(max_length=128, null=True, verbose_name='название')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='universities.region')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('region__name', 'name'),
                'unique_together': {('region', 'name'), ('region', 'name_kk'), ('region', 'name_ru')},
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('name_ru', models.CharField(max_length=256, null=True, verbose_name='название')),
                ('name_kk', models.CharField(max_length=256, null=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('website', models.URLField(blank=True, verbose_name='сайт')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='universities.city')),
            ],
            options={
                'verbose_name': 'ВУЗ',
                'verbose_name_plural': 'ВУЗы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('name_ru', models.CharField(max_length=256, null=True, verbose_name='название')),
                ('name_kk', models.CharField(max_length=256, null=True, verbose_name='название')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='код')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('threshold_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='проходной балл (прошлый год)')),
                ('required_subjects', models.ManyToManyField(blank=True, related_name='for_specialities', to='learning.subject')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='universities.university')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ('university__name', 'name'),
                'indexes': [models.Index(fields=['threshold_score'], name='universitie_thresho_c7b622_idx')],
            },
        ),
    ]
