# Generated by Django 5.1.15 on 2026-04-28 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ENTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('single_choice', 'Один правильный'), ('multi_choice', 'Несколько правильных'), ('match', 'На соответствие'), ('context', 'Контекстное')], max_length=16, verbose_name='тип')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=8, verbose_name='сложность')),
                ('text', models.TextField(verbose_name='текст')),
                ('options', models.JSONField(default=list, verbose_name='варианты')),
                ('correct_answers', models.JSONField(default=list, verbose_name='правильные ответы')),
                ('explanation', models.TextField(blank=True, verbose_name='объяснение')),
                ('related_lesson', models.ForeignKey(blank=True, help_text='Урок, к которому относится вопрос (для рекомендаций по работе над ошибками)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ent_questions', to='learning.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ent_questions', to='learning.subject')),
            ],
            options={
                'verbose_name': 'Вопрос ЕНТ',
                'verbose_name_plural': 'Вопросы ЕНТ',
            },
        ),
        migrations.CreateModel(
            name='ENTTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='конец')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='итоговый балл')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('finished', 'Завершён'), ('expired', 'По таймеру')], default='in_progress', max_length=16, verbose_name='статус')),
                ('profile_subject_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_first_profile_in_sessions', to='learning.subject')),
                ('profile_subject_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_second_profile_in_sessions', to='learning.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия ЕНТ',
                'verbose_name_plural': 'Сессии ЕНТ',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ENTSubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=0, verbose_name='балл')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='ошибок')),
                ('time_seconds', models.PositiveIntegerField(default=0, verbose_name='время (сек)')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ent_results', to='learning.subject')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='testing.enttestsession')),
            ],
            options={
                'verbose_name': 'Результат по предмету',
                'verbose_name_plural': 'Результаты по предметам',
            },
        ),
        migrations.CreateModel(
            name='ENTAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_answer', models.JSONField(default=list, verbose_name='ответ ученика')),
                ('is_correct', models.BooleanField(default=False, verbose_name='верно')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='время (сек)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_answers', to='testing.entquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.enttestsession')),
            ],
            options={
                'verbose_name': 'Ответ в ЕНТ',
                'verbose_name_plural': 'Ответы в ЕНТ',
            },
        ),
        migrations.AddIndex(
            model_name='entquestion',
            index=models.Index(fields=['subject', 'difficulty'], name='testing_ent_subject_6e71d2_idx'),
        ),
        migrations.AddIndex(
            model_name='enttestsession',
            index=models.Index(fields=['user', '-started_at'], name='testing_ent_user_id_090f82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entsubjectresult',
            unique_together={('session', 'subject')},
        ),
        migrations.AddIndex(
            model_name='entanswer',
            index=models.Index(fields=['session', 'question'], name='testing_ent_session_a76d11_idx'),
        ),
    ]
