# Generated by Django 5.1.15 on 2026-04-28 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='заметка')),
                ('manager', models.ForeignKey(limit_choices_to={'role__in': ['sales_manager', 'super_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_notes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_notes', to='profiles.studentprofile')),
            ],
            options={
                'verbose_name': 'Заметка менеджера',
                'verbose_name_plural': 'Заметки менеджера',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['student', '-created_at'], name='crm_salesno_student_f4f61e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(blank=True, max_length=16, verbose_name='старый статус')),
                ('new_status', models.CharField(max_length=16, verbose_name='новый статус')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_status_changes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='profiles.studentprofile')),
            ],
            options={
                'verbose_name': 'Смена статуса клиента',
                'verbose_name_plural': 'Смены статуса клиента',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['student', '-created_at'], name='crm_statusc_student_dcaaf8_idx')],
            },
        ),
    ]
