# Generated by Django 5.1.15 on 2026-04-28 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='название')),
                ('name_kk', models.CharField(max_length=128, null=True, verbose_name='название')),
                ('type', models.CharField(choices=[('clothing', 'Одежда'), ('accessory', 'Аксессуар'), ('armor', 'Броня'), ('weapon', 'Оружие')], max_length=16, verbose_name='тип')),
                ('rarity', models.CharField(choices=[('common', 'Базовый'), ('improved', 'Улучшенный'), ('rare', 'Редкий')], max_length=16, verbose_name='редкость')),
                ('image_url', models.URLField(blank=True, verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Предмет аватара',
                'verbose_name_plural': 'Предметы аватара',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('bronze', 'Бронза'), ('silver', 'Серебро'), ('gold', 'Золото')], max_length=8, unique=True, verbose_name='код')),
                ('min_stars', models.PositiveIntegerField(verbose_name='минимум звёзд')),
                ('max_stars', models.PositiveIntegerField(verbose_name='максимум звёзд')),
            ],
            options={
                'verbose_name': 'Лига',
                'verbose_name_plural': 'Лиги',
                'ordering': ('min_stars',),
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('weekly', 'Еженедельный'), ('event', 'Событие')], max_length=16, verbose_name='тип')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('active', 'Активный'), ('finished', 'Завершён')], max_length=16, verbose_name='статус')),
                ('starts_at', models.DateTimeField(verbose_name='начало')),
                ('ends_at', models.DateTimeField(verbose_name='конец')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='название')),
                ('title_kk', models.CharField(max_length=256, null=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('target_metric', models.CharField(help_text='напр. lessons_completed, stars_earned, tests_passed', max_length=64, verbose_name='метрика')),
                ('target_value', models.PositiveIntegerField(verbose_name='целевое значение')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='дедлайн')),
                ('scope', models.CharField(choices=[('global', 'Глобальный'), ('clan', 'Клан'), ('user', 'Личный')], max_length=16, verbose_name='область')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Челлендж',
                'verbose_name_plural': 'Челленджи',
            },
        ),
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='открыт')),
                ('contained_items', models.ManyToManyField(blank=True, to='gamification.avataritem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сундук',
                'verbose_name_plural': 'Сундуки',
            },
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='рейтинг')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_clans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клан',
                'verbose_name_plural': 'Кланы',
                'ordering': ('-rating',),
            },
        ),
        migrations.CreateModel(
            name='ClanBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('3v3', '3 vs 3'), ('5v5', '5 vs 5'), ('10v10', '10 vs 10')], max_length=8, verbose_name='формат')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('in_progress', 'В процессе'), ('finished', 'Завершена')], default='scheduled', max_length=16, verbose_name='статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='начало')),
                ('clan_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_a', to='gamification.clan')),
                ('clan_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_b', to='gamification.clan')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to='gamification.clan')),
            ],
            options={
                'verbose_name': 'Битва кланов',
                'verbose_name_plural': 'Битвы кланов',
            },
        ),
        migrations.AddField(
            model_name='avataritem',
            name='required_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlockable_items', to='gamification.league'),
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipped_items', models.ManyToManyField(blank=True, related_name='equipped_by', to='gamification.avataritem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аватар пользователя',
                'verbose_name_plural': 'Аватары пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='gamification.league')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лига пользователя',
                'verbose_name_plural': 'Лиги пользователей',
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='прогресс')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='завершено')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gamification.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник челленджа',
                'verbose_name_plural': 'Участники челленджей',
                'unique_together': {('challenge', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ClanMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='вступил')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gamification.clan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник клана',
                'verbose_name_plural': 'Участники кланов',
                'unique_together': {('clan', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дружба',
                'verbose_name_plural': 'Дружбы',
                'unique_together': {('user_a', 'user_b')},
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveSmallIntegerField(verbose_name='кол-во (1-3)')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='получено')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_stars', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Звезда',
                'verbose_name_plural': 'Звёзды',
                'indexes': [models.Index(fields=['user', '-earned_at'], name='gamificatio_user_id_a57d69_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=0, verbose_name='счёт')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='позиция')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gamification.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник турнира',
                'verbose_name_plural': 'Участники турниров',
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
